apiVersion: apps/v1
kind: Deployment
metadata:
  name: serve-model
spec:
  selector:
    matchLabels:
      app: serve-model
  replicas: 2
  template:
    metadata:
      labels:
        app: serve-model
    spec:
      containers:
      - name: serve-model
        image: rikkraan/train_model:v2
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: serve-model
  labels:
    app: serve-model
spec:
  type: NodePort
  selector:
    app: serve-model
  ports:
  - port: 5000
    targetPort: 5000
